language: node_js
node_js:
  - "node"

addons:
  apt:
    packages:
      - xvfb
      - xvfb-run

before_script:
  - 'chmod a+x ./script/travis-build.sh'
  - './node_modules/.bin/electron-rebuild'

script: ./script/travis-build.sh

after_failure: 'npm run mailgun'

env:
  - CXX=g++-4.8
  - DISPLAY=:99.0
  - ENVNAME='travis'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
